---
functional:
  - Пользователь должен иметь возможность просматривать свою статистику
  - Пользователь должен иметь возможность создать матч с ботом
  - Пользователь должен иметь возможность создать матч с другом
  - Пользователь должен иметь возможность принимать приглашения на матч от других игроков
  - Пользователь должен иметь возможность просматриавть таблицу лидеров за разные периоды
  - На сайте должно быть поле для авторизации и регистрации пользователя
non-functional:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Должна быть возможность связаться с поддержкой сайта
  - У сайта должна быть возможность смены языка
